# Generated by Django 4.1.1 on 2022-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_details_delete_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
