# Generated by Django 4.1.1 on 2022-11-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_info_delete_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='email',
            new_name='fname',
        ),
    ]
