# Generated by Django 4.1.1 on 2022-11-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_rename_email_info_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='password1',
            new_name='password',
        ),
    ]
