# Generated by Django 4.1.1 on 2022-11-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_rename_password_info_pass1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
