# Generated by Django 4.1.1 on 2022-11-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
